// ============================================================
// UI - Upload, header controls, modals, search
// ============================================================

import { parseSpoilerLog, transformZonesFromApi, transformLinksFromApi } from './api.js';
import * as State from './state.js';
import * as Exploration from './exploration.js';
import * as Toast from './toast.js';
import { restoreLastVisualState } from './sync/index.js';

// ============================================================
// DOM ELEMENTS
// ============================================================

const uploadScreen = document.getElementById('upload-screen');
const mainUI = document.getElementById('main-ui');
const dropZone = document.getElementById('drop-zone');
const fileInput = document.getElementById('file-input');
const errorMessage = document.getElementById('error-message');
const newFileBtn = document.getElementById('new-file-btn');
const searchInput = document.getElementById('search');
const searchDropdown = document.getElementById('search-dropdown');
const searchClearBtn = document.getElementById('search-clear');

// Show/hide clear button based on search input content
function updateSearchClearButton() {
    if (searchClearBtn) {
        searchClearBtn.classList.toggle('hidden', !searchInput.value.trim());
    }
}

// ============================================================
// FILE UPLOAD
// ============================================================

function showError(msg) {
    errorMessage.innerHTML = msg;
}

function clearError() {
    errorMessage.innerHTML = '';
}

// Process spoiler log text (common logic for files and demo)
async function processSpoilerLogText(text) {
    // Quick client-side validation for better UX
    const hasFogPatterns = text.includes('Preexisting:');
    const hasScaling = text.includes('scaling:');

    if (!hasFogPatterns && !hasScaling) {
        if (text.includes('-- Item preset')) {
            throw new Error(
                'This appears to be an <strong>Item Randomizer</strong> spoiler log, not a Fog Randomizer log.<br><br>Please load a spoiler log from the <strong>Fog Gate Randomizer</strong> mod.'
            );
        }
        if (text.includes('-- Enemy preset')) {
            throw new Error(
                'This appears to be an <strong>Enemy Randomizer</strong> spoiler log, not a Fog Randomizer log.<br><br>Please load a spoiler log from the <strong>Fog Gate Randomizer</strong> mod.'
            );
        }
        throw new Error(
            "This does not appear to be a valid Fog Randomizer spoiler log.<br><br>Make sure you're loading the spoiler log generated by the <strong>Fog Gate Randomizer</strong> mod."
        );
    }

    // Parse via API
    const apiData = await parseSpoilerLog(text);

    // Set starting zone before loading exploration state
    if (apiData.starting_zone_id) {
        State.setStartNodeId(apiData.starting_zone_id);
    }

    // Transform API response to frontend format
    const parsedData = {
        nodes: transformZonesFromApi(apiData.zones),
        links: transformLinksFromApi(apiData.zone_links),
        metadata: {
            seed: apiData.seed,
            startingZoneId: apiData.starting_zone_id,
        },
    };

    if (parsedData.nodes.length === 0) {
        throw new Error('No areas found in the log file.');
    }

    // Show main UI
    uploadScreen.classList.add('hidden');
    mainUI.classList.add('visible');

    // Reset search
    searchInput.value = '';

    // Set seed BEFORE render so exploration state can be loaded
    const newSeed = parsedData.metadata.seed;
    State.setSeed(newSeed);

    // Check if we already have saved graph data for this seed (preserves UUIDs)
    const existingGraphData = State.loadGraphFromStorage(newSeed);
    const graphData = existingGraphData || parsedData;

    // Store graph data
    State.setGraphData(graphData);

    // Save to localStorage only if this is a new seed
    if (!existingGraphData) {
        State.saveGraphToStorage();
    }

    // Update URL with seed parameter in offline mode (enables refresh/bookmark)
    if (State.getBackendMode() === 'offline') {
        const newUrl = `/?offline=true&seed=${newSeed}`;
        history.replaceState(null, '', newUrl);
    }

    // Load exploration state BEFORE render (if saved), or initialize
    if (State.isExplorationMode()) {
        if (!Exploration.loadExplorationState(newSeed)) {
            Exploration.initExplorationState();
        }
    }

    // Trigger render
    State.emit('graphNeedsRender', { preservePositions: false });

    // Update UI controls based on current mode
    updateModeButtons();
}

/**
 * Load a saved offline game by seed.
 * @param {string} seed - The seed to load
 * @returns {boolean} True if game was loaded, false otherwise
 */
export function loadOfflineGame(seed) {
    const graphData = State.loadGraphFromStorage(seed);
    if (!graphData) return false;

    // Show main UI
    uploadScreen.classList.add('hidden');
    mainUI.classList.add('visible');

    // Reset search
    searchInput.value = '';

    // Set seed and graph data
    State.setSeed(seed);
    State.setGraphData(graphData);

    // Load exploration state
    if (State.isExplorationMode()) {
        if (!Exploration.loadExplorationState(seed)) {
            Exploration.initExplorationState();
        }
    }

    // Trigger render
    State.emit('graphNeedsRender', { preservePositions: false });

    // Update UI controls
    updateModeButtons();

    return true;
}

function handleFile(file) {
    clearError();

    if (!file) {
        showError('No file selected');
        return;
    }

    const reader = new FileReader();

    reader.onload = async e => {
        try {
            await processSpoilerLogText(e.target.result);
        } catch (err) {
            console.error(err);
            showError(err.message || `Error parsing the log file: ${err}`);
        }
    };

    reader.onerror = () => {
        showError('Error reading the file.');
    };

    reader.readAsText(file);
}

async function loadDemoData() {
    clearError();

    try {
        const response = await fetch('data/demo_log.txt');
        if (!response.ok) {
            throw new Error('Demo file not found');
        }
        const text = await response.text();
        await processSpoilerLogText(text);
    } catch (err) {
        console.error(err);
        showError(`Error loading demo: ${err.message}`);
    }
}

// ============================================================
// SEARCH
// ============================================================

function handleSearch(query) {
    if (!query) {
        searchDropdown.classList.remove('visible');
        searchDropdown.innerHTML = '';
        State.emit('searchCleared');
        return;
    }

    const graphData = State.getGraphData();
    if (!graphData) return;

    // Find matching nodes (search on display name, fallback to id)
    const matching = graphData.nodes.filter(n => (n.name || n.id).toLowerCase().includes(query.toLowerCase()));

    State.emit('searchMatched', { matchingIds: new Set(matching.map(n => n.id)) });

    // Show dropdown with undiscovered matches in exploration mode (not for viewers)
    if (State.isExplorationMode() && !State.isViewerMode()) {
        const explorationState = State.getExplorationState();
        const undiscoveredMatches = matching.filter(n => !explorationState.discovered.has(n.id));

        if (undiscoveredMatches.length > 0) {
            let html = '';
            undiscoveredMatches.slice(0, 8).forEach(n => {
                html += `
                    <div class="search-result">
                        <div>
                            <span class="search-result-name">${n.name || n.id}</span>
                            <span class="search-result-status">(not discovered)</span>
                        </div>
                        <button class="search-result-btn" data-node-id="${n.id}">🎯 I've reached</button>
                    </div>
                `;
            });
            if (undiscoveredMatches.length > 8) {
                html += `<div class="search-result"><span class="search-result-status">... and ${undiscoveredMatches.length - 8} more</span></div>`;
            }
            searchDropdown.innerHTML = html;
            searchDropdown.classList.add('visible');

            // Add click handlers
            searchDropdown.querySelectorAll('.search-result-btn').forEach(btn => {
                btn.addEventListener('click', function () {
                    const nodeId = this.getAttribute('data-node-id');
                    Exploration.discoverPathTo(nodeId);
                    searchInput.value = '';
                    searchDropdown.classList.remove('visible');
                    searchDropdown.innerHTML = '';
                    State.emit('searchCleared');
                });
            });
        } else {
            searchDropdown.classList.remove('visible');
            searchDropdown.innerHTML = '';
        }
    }
}

// ============================================================
// MODE SWITCHING
// ============================================================

function updateModeButtons() {
    const modeSpoilerBtn = document.getElementById('mode-spoiler');
    const modeExplorerBtn = document.getElementById('mode-explorer');
    const explorerControls = document.getElementById('explorer-controls');
    const frontierCheckbox = document.getElementById('show-frontier-checkbox');

    const explorationMode = State.isExplorationMode();

    if (explorationMode) {
        modeExplorerBtn.classList.add('active');
        modeSpoilerBtn.classList.remove('active');
        explorerControls.classList.remove('hidden');
    } else {
        modeSpoilerBtn.classList.add('active');
        modeExplorerBtn.classList.remove('active');
        explorerControls.classList.add('hidden');
    }

    // Reset frontier checkbox state
    if (frontierCheckbox) {
        frontierCheckbox.checked = false;
    }
    State.setFrontierHighlightActive(false);
}

function switchToSpoilerMode() {
    if (!State.isExplorationMode()) return;

    State.setExplorationMode(false);
    updateModeButtons();

    State.emit('graphNeedsRender', { preservePositions: true });
}

function switchToExplorerMode() {
    if (State.isExplorationMode()) return;

    State.setExplorationMode(true);
    updateModeButtons();

    // Load existing save or initialize
    const seed = State.getSeed();
    if (seed && !Exploration.loadExplorationState(seed)) {
        Exploration.initExplorationState();
    }

    State.emit('graphNeedsRender', { preservePositions: true });
}

// ============================================================
// FRONTIER HIGHLIGHT
// ============================================================

export function highlightFrontier() {
    const explorationState = State.getExplorationState();
    const graphData = State.getGraphData();
    if (!explorationState || !graphData) return;

    const svg = d3.select('#graph-container svg');
    const nodes = svg.selectAll('.node');
    const links = svg.selectAll('.link');

    // Find access nodes (discovered nodes that have undiscovered neighbors)
    const accessNodes = new Set();

    graphData.links.forEach(link => {
        const { sourceId, targetId } = State.getLinkEndpoints(link);

        const sourceDiscovered = explorationState.discovered.has(sourceId);
        const targetDiscovered = explorationState.discovered.has(targetId);

        if (sourceDiscovered && !targetDiscovered) {
            accessNodes.add(sourceId);
        } else if (!sourceDiscovered && targetDiscovered && !link.oneWay) {
            accessNodes.add(targetId);
        }
    });

    // Also check placeholders for undiscovered links (between two discovered nodes)
    // These placeholders have a sourceNodeId that should be an access node
    nodes.each(d => {
        if (d.isPlaceholder && d.sourceNodeId) {
            accessNodes.add(d.sourceNodeId);
        }
    });

    // Apply frontier highlights - only when nothing is selected
    // placeholder nodes (isPlaceholder) are frontier nodes
    nodes
        .classed('frontier-highlight', d => d.isPlaceholder === true)
        .classed('access-highlight', d => accessNodes.has(d.id))
        .classed('highlighted', false)
        .classed('dimmed', d => !d.isPlaceholder && !accessNodes.has(d.id));

    // Links to placeholder nodes are frontier links
    links
        .classed('frontier-highlight', l => {
            const { sourceId, targetId } = State.getLinkEndpoints(l);
            return sourceId.startsWith('???_') || targetId.startsWith('???_');
        })
        .classed('highlighted', false)
        .classed('dimmed', l => {
            const { sourceId, targetId } = State.getLinkEndpoints(l);
            const isToPlaceholder = sourceId.startsWith('???_') || targetId.startsWith('???_');
            return !isToPlaceholder;
        });
}

export function clearFrontierHighlight() {
    const svg = d3.select('#graph-container svg');
    svg.selectAll('.node')
        .classed('frontier-highlight', false)
        .classed('access-highlight', false)
        .classed('dimmed', false)
        .classed('highlighted', false);
    svg.selectAll('.link').classed('frontier-highlight', false).classed('dimmed', false).classed('highlighted', false);

    // Restore selection highlight if a node is selected
    State.emit('restoreSelectionHighlight');
}

function onFrontierCheckboxChange(checked) {
    if (!State.isExplorationMode() || !State.getGraphData()) return;

    State.setFrontierHighlightActive(checked);

    if (checked) {
        highlightFrontier();
    } else {
        clearFrontierHighlight();
    }
}

// ============================================================
// EVENT LISTENERS SETUP
// ============================================================

export function initUI() {
    // File upload
    dropZone.addEventListener('click', () => fileInput.click());

    fileInput.addEventListener('change', e => {
        handleFile(e.target.files[0]);
    });

    dropZone.addEventListener('dragover', e => {
        e.preventDefault();
        dropZone.classList.add('dragover');
    });

    dropZone.addEventListener('dragleave', e => {
        e.preventDefault();
        dropZone.classList.remove('dragover');
    });

    dropZone.addEventListener('drop', e => {
        e.preventDefault();
        dropZone.classList.remove('dragover');
        handleFile(e.dataTransfer.files[0]);
    });

    // New file button
    newFileBtn.addEventListener('click', () => {
        mainUI.classList.remove('visible');
        uploadScreen.classList.remove('hidden');
        fileInput.value = '';
        clearError();

        const sim = State.getSimulation();
        if (sim) sim.stop();
    });

    // Demo button
    const demoBtn = document.getElementById('demo-btn');
    if (demoBtn) {
        demoBtn.addEventListener('click', loadDemoData);
    }

    // Search
    searchInput.addEventListener('input', e => {
        handleSearch(e.target.value);
        updateSearchClearButton();
    });

    // Search clear button
    if (searchClearBtn) {
        searchClearBtn.addEventListener('click', () => {
            searchInput.value = '';
            searchInput.focus();
            searchDropdown.classList.remove('visible');
            searchDropdown.innerHTML = '';
            updateSearchClearButton();
            State.emit('searchCleared');
        });
    }

    document.addEventListener('click', e => {
        if (!e.target.closest('#search-container')) {
            searchDropdown.classList.remove('visible');
        }
    });

    // Mode buttons
    const modeSpoilerBtn = document.getElementById('mode-spoiler');
    const modeExplorerBtn = document.getElementById('mode-explorer');

    modeSpoilerBtn.addEventListener('click', switchToSpoilerMode);
    modeExplorerBtn.addEventListener('click', switchToExplorerMode);

    // Reset button
    const resetBtn = document.getElementById('reset-exploration-btn');
    resetBtn.addEventListener('click', () => {
        if (confirm('Reset your exploration progress? All discovered areas and tags will be lost.')) {
            Exploration.resetExplorationState();
        }
    });

    // Frontier checkbox
    const frontierCheckbox = document.getElementById('show-frontier-checkbox');
    if (frontierCheckbox) {
        frontierCheckbox.addEventListener('change', () => {
            onFrontierCheckboxChange(frontierCheckbox.checked);
        });
    }

    // Path from start checkbox
    const pathCheckbox = document.getElementById('show-path-from-start');
    if (pathCheckbox) {
        pathCheckbox.addEventListener('change', () => {
            State.emit('pathFromStartChanged', pathCheckbox.checked);
        });
    }

    // Helper to clear search
    function clearSearch() {
        searchInput.value = '';
        searchInput.blur();
        searchDropdown.classList.remove('visible');
        searchDropdown.innerHTML = '';
        updateSearchClearButton();
        State.emit('searchCleared');
    }

    // Keyboard shortcuts
    document.addEventListener('keydown', e => {
        // Escape: clear search if active, otherwise close tooltip
        if (e.key === 'Escape') {
            // If in search input, clear and blur
            if (e.target === searchInput) {
                clearSearch();
                e.preventDefault();
                return;
            }

            // Ignore if typing in other input fields
            if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return;

            // If search has text, clear it first
            if (searchInput.value.trim()) {
                clearSearch();
                e.preventDefault();
                return;
            }

            // Otherwise close tooltip
            const closeBtn = document.querySelector('#tooltip.visible .close-btn');
            if (closeBtn) {
                closeBtn.click();
                e.preventDefault();
            }
            return;
        }

        // Ignore other keys if typing in an input field
        if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return;

        // Ignore if no graph loaded
        if (!State.getGraphData()) return;

        const key = e.key.toLowerCase();

        // D: Discover selected placeholder
        if (key === 'd') {
            const discoverBtn = document.querySelector('#tooltip.visible .discover-btn');
            if (discoverBtn) {
                discoverBtn.click();
                e.preventDefault();
            }
            return;
        }

        // U: Undiscover selected node
        if (key === 'u') {
            const undiscoverBtn = document.querySelector('#tooltip.visible .undiscover-btn');
            if (undiscoverBtn) {
                undiscoverBtn.click();
                e.preventDefault();
            }
            return;
        }

        // F: Toggle frontier highlight
        if (key === 'f') {
            if (!State.isExplorationMode()) return;

            const frontierCheckbox = document.getElementById('show-frontier-checkbox');
            if (frontierCheckbox) {
                frontierCheckbox.checked = !frontierCheckbox.checked;
                onFrontierCheckboxChange(frontierCheckbox.checked);
                e.preventDefault();
            }
            return;
        }

        // P: Toggle path from start
        if (key === 'p') {
            const pathCheckbox = document.getElementById('show-path-from-start');
            if (pathCheckbox) {
                pathCheckbox.checked = !pathCheckbox.checked;
                State.emit('pathFromStartChanged', pathCheckbox.checked);
                e.preventDefault();
            }
            return;
        }
    });

    // Window resize
    let resizeTimeout;
    window.addEventListener('resize', () => {
        if (State.getGraphData() && mainUI.classList.contains('visible')) {
            clearTimeout(resizeTimeout);
            resizeTimeout = setTimeout(() => {
                State.saveAllNodePositions();
                State.emit('graphNeedsRender', { preservePositions: true });
            }, 150);
        }
    });

    // Subscribe to state events
    State.subscribe('explorationReset', () => {
        State.emit('graphNeedsRender', { preservePositions: false });
    });

    // Re-apply frontier highlight after graph render if it's active AND nothing is selected
    // Overlay viewers get highlights from host, everyone else calculates locally
    State.subscribe('graphRenderCompleted', () => {
        if (State.isFrontierHighlightActive() && !State.getSelectedNodeId() && !State.isOverlayMode()) {
            highlightFrontier();
        }
    });

    // Re-apply frontier highlight when selection is cleared
    State.subscribe('restoreFrontierHighlight', () => {
        if (State.isFrontierHighlightActive()) {
            if (State.isOverlayMode()) {
                // Overlay viewer: restore host's visual state (don't recalculate)
                restoreLastVisualState();
            } else {
                // Host, interactive viewer, or not connected: recalculate locally
                highlightFrontier();
            }
        }
    });

    // Update UI based on frontier state changes
    State.subscribe('frontierHighlightChanged', active => {
        const frontierCheckbox = document.getElementById('show-frontier-checkbox');
        if (frontierCheckbox) {
            frontierCheckbox.checked = active;
        }

        // Overlay viewers receive visual classes from host via applyVisualClasses()
        // Everyone else (host, interactive viewer, not connected) calculates locally
        if (!State.isOverlayMode()) {
            if (active) {
                highlightFrontier();
            } else {
                clearFrontierHighlight();
            }
        }
    });
}

// ============================================================
// EXPORTS
// ============================================================

export { showError, clearError, handleFile, updateModeButtons };
